version: "3"

services:
  nginx:
    image: nginx:1.23.0-alpine
    container_name: "ishdi_nginx"
    volumes:
      - ./local/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./local/nginx/site1.conf:/etc/nginx/conf.d/default.conf
      - ./local/nginx/site2.conf:/etc/nginx/conf.d/site2.conf
      - ./local/nginx/site3.conf:/etc/nginx/conf.d/site3.conf
      - ..:/var/www/html:cached
    working_dir: /var/www/html
    ports:
      - "80:80"
    networks:
      localdev:
        aliases:
          - site1.dev
          - site2.dev
          - site3.dev

  php:
    build: ./local/php
    container_name: "ishdi_php"
    ports:
      - "9000:9000"
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - ../site1:/var/www/html/site1:cached
      - ../site2:/var/www/html/site2:cached
      - ../site3:/var/www/html/site3:cached
    working_dir: /var/www/html
    networks:
      - localdev

networks:
  localdev:
